In [2]:
import torch

In [5]:
randint1 = torch.randint(-100,100,(6,))
randint2 = torch.randint(10,(5,5))
randint3 = torch.randint(3,8,(2,4))
print('1:', randint1)
print('2:', randint2)
print('3:', randint3)

1: tensor([ 65, -35,  22,  75,  45, -29])
2: tensor([[8, 8, 6, 4, 0],
        [3, 4, 0, 2, 6],
        [6, 0, 5, 4, 7],
        [8, 5, 3, 9, 4],
        [7, 2, 1, 9, 4]])
3: tensor([[7, 3, 7, 3],
        [5, 7, 4, 6]])


In [6]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [7]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
torch.empty((2,3), dtype=torch.int64)

#this differs from the tutorial output, for him it was a 2x3
#array of very large decimal numbers, ex: [0,0]=> 1.6689e+22
#for my own posterity, all of the numbers looked like that

tensor([[0, 0, 0],
        [0, 0, 0]])

In [10]:
a_range = torch.arange(7)
a_range

tensor([0, 1, 2, 3, 4, 5, 6])

In [11]:
linspace = torch.linspace(3,10, steps=5)
linspace
#linear increments up from 3 to 10

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [13]:
logspace = torch.logspace(start=3,end=10,steps=5)
logspace

tensor([1.0000e+03, 5.6234e+04, 3.1623e+06, 1.7783e+08, 1.0000e+10])

In [14]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])