In [2]:
import torch

In [9]:
randint1 = torch.randint(-100,100,(6,))
randint2 = torch.randint(10,(5,5))
randint3 = torch.randint(3,8,(2,4))
print('1:', randint)
print('2:', randint2)
print('3:', randint3)

1: tensor([-33,  63, -79,  20,  30,  76])
2: tensor([[9, 0, 0, 0, 8],
        [8, 6, 0, 1, 9],
        [3, 8, 9, 6, 4],
        [2, 8, 4, 5, 0],
        [8, 8, 7, 7, 3]])
3: tensor([[5, 4, 4, 3],
        [3, 7, 6, 7]])


In [11]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [12]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
torch.empty((2,3), dtype=torch.int64)

#this differs from the tutorial output, for him it was a 2x3
#array of very large decimal numbers, ex: [0,0]=> 1.6689e+22
#for my own posterity, all of the numbers looked like that

tensor([[0, 0, 0],
        [0, 0, 0]])